name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Check out the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Load Environment Variables
      - name: Setup Environment Variables
        run: echo "VUE_APP_TMDB_API_KEY=${{ secrets.TMDB_API_KEY }}" >> $GITHUB_ENV

      # Install dependencies
      - name: Install Dependencies
        run: yarn install

      # Run unit tests
      - name: Run Unit Tests
        env:
          VUE_APP_TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        run: yarn test:unit

      # Run lint checks
      - name: Run Linter
        run: yarn lint
